### ISSUE TITLE
About Cora dataset and Citeseer dataset

### ISSUE THREAD

**Issue by heguodui** [malllabiisc/HyperGCN#2]
Hello, your work is very good and very valuable for research. Can you provide the Cora dataset and Citeseer dataset that you have processed in the paper?

**Comment by naganandy** [comment]
Hi, Thanks for the interest in our paper. The datasets have been uploaded to the [data directory](https://github.com/malllabiisc/HyperGCN/tree/master/data).

**Comment by giuliacassara** [comment]
Hi! Can you provide the script of the procedure to build the datasets?
